FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

# Run the app. No need to pass port/host args since code handles env vars.
CMD ["python", "main.py"]